## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('bayes', ['olsr','wifi'])
    module.includes = '.'
    module.source = [
        'model/bayes.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'bayes'
    headers.source = [
        'model/bayes.h',
	'model/tools-module.h',
        ]
    bld.ns3_python_bindings()

